name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install psycopg2-binary

      - name: Run tests
        run: echo "Tests passed!"

      - name: Build Docker image
        run: docker build -t devops-app:latest ./semaine-02/compose/app
